### ISSUE TITLE
possible missing file

### ISSUE THREAD

**Issue by Kahilli** [ketonereides/wolfdown#1]
When I uploaded everything to http://btm.ghostecho.net/mercury/index.php, but I'm not sure if I've missed a step or what and that's why I'm getting the Warning: file_get_contents(content/Home.markdown) [function.file-get-contents]: failed to open stream: No such file or directory in /home/ghost/public_html/btm/mercury/index.php on line 79 error.

**Comment by ketonereides** [comment]
Fixed! I had deleted it for some reason, but I added it back.
