### ISSUE TITLE
Location Packs

### ISSUE THREAD

**Issue by emaleesoddy** [ketonereides/wolfdown#6]
Unless you want to give it a shot, I'm planning on writing up a location pack for Wolfdown... basically it would convert [fop] into the icon for Fields of Perea, and give the name of the territory on hover. :)

I likely won't get to it until next Wednesday, though, so if it's something you think you can do quickly before then, totally cool with that!

**Comment by ketonereides** [comment]
Sure, go right ahead! I never use icons, so it's not something I'd be motivated to do. :P
